version 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/apps/nodejs
hooks:
  BeforeInstall:
    - location : before_install_script.sh
      runas: root
  ApplicationStart:
    - location : install_script.sh
      runas: root
